### ISSUE TITLE
A few questions about the future of the API

### ISSUE THREAD

**Issue by Sarcasm** [Microsoft/cppgraphqlgen#11]
Hello,

First, thank you for this project!
There is a lot of things going on about GraphQL for many languages, but somehow there is so few projects about it in the C++ ecosystem.

I have been watching the project and the recent changes, and I like the direction it goes.
I have a few questions regarding the future of the API:

1. Do you think it would make sense to provide access to the SelectionSet to the resolvers?
   It feels like it could be useful sometimes to know what fields or subfields will be required to make the right query.
2. One of the thing I find elegant in GraphQL, is how the query execution can be run concurrently in JavaScript and make "optimal" use of the event loop and future/promise JS has. Fields can be resolved concurrently, data loaders can batch requests to the data store, etc.
   I am under the impression that for now cppgraphqlgen does not make it possible to have this kind of concurrency. C++ makes it difficult because the future/promises API from the STL is limited for now (e.g. no `std::future::then()` yet) and there is no event loop (io_context or what not) yet.
   I'd really like to be able to resolve multiple things, blocking on I/O, concurrently. To get better throughput.
   Is is something you have already thought about?
3. Regarding the representation of the results. I see that you recently changed from cpprestsdk to RapidJSON to represent the data. I feel like the GraphQL API does not really mandate JSON, but more like a dynamic object container that can be serialized to JSON. And I'm wondering if this could not be represented simply with some `std::variant` equivalent, or something akin to Folly's Dynamic: https://github.com/facebook/folly/blob/74eb516913af8374a895014e2aa67561cfd1ab46/folly/docs/Dynamic.md
   Maybe an object type that respect the "Serialized Map Ordering" from the GraphQL spec: https://facebook.github.io/graphql/June2018/#sec-Serialized-Map-Ordering

**Comment by wravery** [comment]
Glad you like it, and thanks for the PRs. 👍 

Coincidentally, I just started thinking about supporting concurrency this morning, and passing the SelectionSet to the resolver was the approach I was thinking of. Ironically, if I had stayed with cpprestsdk, I'd also have the option of using pplx for parallelism, but it's still a very big dependency. But a more portable implementation could use the SelectionSet as a hint to start prefetching sub-fields before the next resolver is called, using whatever concurrency framework they want to parallelize the pre-fetch. So I think 1 and 2 would go together pretty well.

I also considered making a abstraction of the JSON DOM (including `std::variant`, althouhg that would leave behind C++11 support) and then coding the RapidJSON support against it as an optional implementation to get away from the cpprestsdk dependency. As I got into it, I found that RapidJSON semantics are very different from other libraries, and it really steers you away from memory copies. I'm still open to the idea of abstracting the JSON DOM, but I want to put some more thought into how I can continue to support the minimal memory copies in RapidJSON in the process. It might turn out that I can build the entire document using move semantics and defer all copies until I'm actually ready to render it through a JSON library (which would then be pluggable).

**Comment by Sarcasm** [comment]
I do agree with 1 and 2 being related, and having either one can make the other less or not needed.
With the selection set and prefetching, I guess it's possible to complete a single request in a minimal amount of time/work necessary.
Is it safe to make multiple service::Request::resolve() in parallel?
I'm under the impression that it is possible.

Regarding the JSON questions, I was asking because apart from that cppgraphqlgen, is agnostic of the HTTP transport.
I'm curious to use GraphQL not only over HTTP/WebSocket but also things like ZeroMQ.
And while a textual serialization format is useful over HTTP, it is less so over things like ZeroMQ, where one might want to favor a binary serialization format.
I don't think RapidJSON prevent this (for example [nlohmann/json](https://github.com/nlohmann/json) has support for [Binary formats](https://github.com/nlohmann/json/tree/e73dfef6e51b876cbfd8fadb8b6a1771a196b6e8#binary-formats-bson-cbor-messagepack-and-ubjson)), but it can give a false impression that GraphQL implies JSON.

**Comment by wravery** [comment]
For concurrency, I think I can get that working by just changing the `getField` methods to all return `std::future<>` instead of the current type. A default serial implementation would just use `std::promise<>` to package up the same results, but multi-threaded implementations could use `std::async` or `std::packaged_task` with a custom thread management scheme to run them in parallel. The future for each resolver and sub-selection would be fulfilled by waiting for all of the sub-selection futures and slotting the results into the DOM. However, that would make it a little trickier to handle the SelectionSet hint. This might require a couple of optional virtual callbacks to begin and end visiting the SelectionSet. If the service::Object wants to start accumulating state in the begin callback for which `getField` methods were called and potentially which `std::promise<>` results have been returned, it can optimize and execute the query in the end callback.

It should be fine to resolve multiple requests in parallel, as long as the schema specific service::Object implementations are thread safe. There's no built-in protection or synchronization to guarantee safety in the service implementation, but the parts that are built in the `graphqlservice` library should only deal with immutable resolver maps.

I see what you mean about not making it JSON specific. If the results DOM were written in terms of the GraphQL [Serialization Format](https://facebook.github.io/graphql/June2018/#sec-Serialization-Format) types, then I could just create a sample that transforms that to JSON (e.g. with RapidJSON) and avoid serialization overhead or library dependencies/coupling, and it would be more true to the spec.

**Comment by Sarcasm** [comment]
Wow! :)
Didn't expect this to come out so fast.
Thank you. :+1:
