### ISSUE TITLE
Why response::Value::_data is allocated

### ISSUE THREAD

**Issue by barbieri** [microsoft/cppgraphqlgen#128]
Why do we have `response::Value::_data` allocated on demand? Given that it's a `std::variant<>` of the internal types

Allocation https://github.com/microsoft/cppgraphqlgen/blob/master/src/GraphQLResponse.cpp#L70-L96
Variant https://github.com/microsoft/cppgraphqlgen/blob/master/src/GraphQLResponse.cpp#L58-L60

Unless there is a reason I didn't see, I'd propose to unify that in a single memory unit, inlining `_data` or even making that the `response::Value` itself, since we don't even need to hold the `type`, given that we could discover it using `std::variant`, such as `std::holds_alternative`.

**Comment by wravery** [comment]
There are 2 reasons for the current behavior:

- Null values don't require additional storage, by not allocating any it makes them very cheap to construct as temporary objects with the default constructor.
- `std::unique_ptr` supports practically free move semantics by swapping pointers. Semantically speaking, `std::optional` would make sense, but when it contains a value `std::optional` differs from `std::unique_ptr` in that it allocates in-place, so a move would actually need to make a shallow copy of the nested object.

**Comment by barbieri** [comment]
But should we be allocating null values that much? Also we could use a mempool to cache the items, them being of the same size would help a bit even if the value does not use it all.

If we could reduce the `MapType` (as in #130), then it would be not that bad.

As for the unique_ptr semantics ok, but we could change places using `response::Value` to `unique_ptr<TypedData>`, maybe using alias or a typedefs (I'm not a C++ expert). We can infer `type()` from variant type easily.

**Comment by wravery** [comment]
There are a few cases where different `Type` enums use overlapping storage as a side effect of having the same type in the `std::variant`. Specifically, `Enum` and `String` share storage, and we need to be able to treat any `Enum` as a `String` on output, but not the other way around on input (except if it came from JSON since we can't tell in that case and it's maybe an `Enum`). We could probably use explicit types for each one, with special handling for maybe-overlapping types. That would make the `_type` member redundant with the `std::variant` so we could drop it. The `Null` type could be encoded with an empty struct type as well.

BTW, I'm not opposed to any of those changes or the ones you suggest, just explaining the background for the current implementation. As long as it handles all the same functional constraints I'd be happy to at least consider trading some of the optimized move semantics for more compact storage with less indirection.

**Comment by barbieri** [comment]
ok, i'll take a look at  this later, first I'll work on #127 and then tackle this one.

thanks for all the tests, they really help ensuring this kind of change doesn't break code 🙏

**Comment by barbieri** [comment]
while I get the reason to dissociate `_data` from the actual shell, I believe we should employ the COW in this data structures. I'll prepare another PR with just that change so we can compare.

**Comment by barbieri** [comment]
this is fixed
