### ISSUE TITLE
Strings with length constraints / Custom scalars in mutation input

### ISSUE THREAD

**Issue by paussu** [microsoft/cppgraphqlgen#155]
Hi,

I am trying to create a mutation input that would have strings with length constraints.

What would be the best way to implement this?

Is it possible to have constraints for fields like: String @max(length: 10)?

Currently I am trying to implement these length constraints with custom scalars, for example String10. 
In generated schema and input params these fields are defined response::Value.

How do you get this custom scalar from these values?

**Comment by wravery** [comment]
I'm not sure how to build that constraint into a schema definition, but you could certainly define your own directive and interpret it as you see fit in the resolvers. That would mostly be useful for documenting the schema though, because there's no way to tell `cppgraphqlgen` what your directive means.

Generally if I were going to do something like this, I'd check the length in the resolver/apply method. If the limit is exceeded, I'd throw a `std::runtime_error` or `std::invalid_argument` exception from the resolver/apply method with an error message for the caller. The `graphqlservice` library should catch that and bubble it up as a field error in the GraphQL results.

If you want to use a scalar type, that's also kind of opaque to `cppgraphqlgen`, and to most tooling. If you are returning it, whatever `response::Value` you build will get converted to JSON and included in the GraphQL results for that field. If you pass it as an input parameter, I think it will convert whatever value you pass to an equivalent `response::Value` argument/member, and it will be up to you to interpret it. You could pass strings that way, but there aren't conversion hooks that you could use to centralize that limit. If you want to apply it in multiple places, your best bet would probably be to extract a function to do that check and then call it from any resolvers/apply methods which use that type.

**Comment by paussu** [comment]
Thanks, I think I'll create a function to check for specific lengths in the apply methods 🙂
Seems to work great: 
`"message": "Field error name: createTestObject unknown error: exampleField should be under 5 in length"`

**Comment by wravery** [comment]
Great, I'll go ahead and close the issue then.
