### ISSUE TITLE
Is it possible to split graph into subgraphs?

### ISSUE THREAD

**Issue by gitmodimo** [microsoft/cppgraphqlgen#192]
I was wondering if it is possible to split up the graphql schema into subtrees and generate them independently? As in [Apollo federation](https://www.apollographql.com/docs/federation/). I was hoping to keep relevant schema parts in project modules and join them together in main program body using another schema part.

**Comment by wravery** [comment]
Sort of, but not as well defined as Apollo's federation feature, it's a little more like [schema stitching](https://www.apollographql.com/blog/backend/graphql-schema-stitching/). I haven't used this pattern yet, but I think it would work:

Define portions of your schema separately using schema extensions. You can break them up into separate files and maintain them separately, as long as you can concatenate them with a base schema which defines the operation types (i.e. `Query`, `Mutation`, and `Subscription`) without any sub-graph fields when you call `schemagen`/`clientgen`. For development purposes, you might only merge the sub-graph's schema extensions, but then when you actually produce a build, you would merge everything and generate the operation types with references to all of the sub-graphs.

When building the generated C++ files, you can link a subset of them for each sub-graph into a static library (using the `schemagen --separate-files` option in `v3.x`) and test separately. Don't link the operation types in the same library since they'll conflict with other sub-graphs or the stitched together public graph, you can build them into a separate library or just link the object files directly into your test targets. You can implement the operation type field accessors as stand-alone functions or methods on a separate sub-graph type which you define for reuse, so for instance `Query::getSubField` in the sub-graph implementation might just call a `SubGraphFooQuery::getSubField` method.

To produce a production build, re-generate the operation types from the concatenated schema. Implement the field accessors on the unified operation types (mapping `Query::getSubField` to the reusable `SubGraphFooQuery::getSubField` in the previous example). Build and link the operation types from the concatenated schema, but instead of building and linking all of the other generated `.cpp` files from that schema, link in each of the static libraries you created for the sub-graphs.

**Comment by gitmodimo** [comment]
I think I got it. Can you confirm my understanding?
Lets assume I use preprocessor on *.graphql files in order to handle includes (I do not see out of box solution) and I generate files using `schemagen --separate-files`. 
Given files:
**base.graphql**
```
type Query{
}

type Mutation{
}

type Subscription{
}
```

**moduleA.graphql**
```
#include "base.graphql"
extend type Query{
	fieldA: Float!
}

extend type Mutation{
	fieldA: Float!
}

extend type Subscription{
	fieldA: Float!
}
```


**moduleB.graphql**
```
#include "base.graphql"
extend type Query{
	fieldB: String!
}

extend type Mutation{
	fieldB: String!
}

extend type Subscription{
	fieldB: String!
}
```
**schema.graphql**
```
#include "base.graphql"
#include "moduleA.graphql
#include "moduleB.graphql"
```


In order to compile and link:
1. generate code using moduleA.graphql, then compile everything except Schema.cpp
2. generate code using moduleB.graphql, then compile everything except Schema.cpp
3. generate code using schema.graphql, then compile only Schema.cpp
4. link it all together

It also seems like all modules have to use the same namespace. But i think I can live with that.

**Comment by wravery** [comment]
Pretty much, yes. You could also define shared types in `base.graphql` besides the operation types, so that way moduleA and moduleB could both see them.

The `schemagen` tool won't process the `#include` directives, but you can probably either get the C/C++ preprocessor to do it, or replace that with a shell script that just concatenates the files. CMake's `configure_file` might even work for this purpose, you would need to replace them with `@TOKEN_NAME@` for that.

For steps 1 and 2, you could also build separate tests by including in the `...Schema.cpp` files, but the library you build from each module should leave it out like you say. When they are all linked together in step 3, the merged `schema/...Schema.cpp` file would replace the per-module versions. So, what you have there will work, but you can avoid compiling the same sources more than once by building static libs in step 1 and 2, and only compiling + linking each `...Schema.cpp` version with a single target which is not part of a static library.

If you do have shared types in `base.graphql`, you would also need to hoist them into their own static library + headers that both moduleA and moduleB consume as `PUBLIC` linked targets in CMake (or the equivalent for your build system if not CMake). That way targets which link with moduleA or moduleB, like schema, would also link with the static library you build for `base.graphql`.

**Comment by gitmodimo** [comment]
> For steps 1 and 2, you could also build separate tests by including...

Makes sense.

> If you do have shared types in base.graphql,...

If I move shared types into `base.graphql` their corresponding files get generated in both modules. Then I would have to cherry pick files for compilation.  
Is there downside (that I am not seeing) of using headers from schema/ in moduleB? I only need one way dependency(this should work both ways anyways). Any change in `moduleA.graphql` schema will require moduleB rebuild as if `base.graphql` had changed, but this is acceptable.

**Comment by wravery** [comment]
I see, you are correct. I think the downside to not cherry-picking files for compilation is that you'd end up with duplicate symbols in moduleA and moduleB for anything that was part of the shared base. You may not be able to link both modules together as static libs, so you'd have to recompile everything in the merged schema instead.

The cherry-picking can be automated though. If you build and link a static lib for the shared base schema, just like moduleA and moduleB, then moduleA and moduleB can use wildcards to remove any filenames that were included in base. You couldn't use the [add_graphql_schema_target](https://github.com/microsoft/cppgraphqlgen/blob/e597db3efa62719e05950449009c98a052952c0d/cmake/cppgraphqlgen-functions.cmake#L41) function directly in moduleA/moduleB, but it would look very similar to how that is implemented. It would need to read the file list for its own module, then read the file list for base, and remove any files which appear in base.

**Comment by gitmodimo** [comment]
Turns out you are right. Without common types in base I could not generate subgraphs since they need to 'see' common types in graphs. 
Other than that it seems to work very nice! Thanks!
Anyways, I think it could be considered I future to add the possibility to dynamically expand the graphs. Their structure is build in runtime so this should not be to hard allow adding new types and files to existing schema.
My dream is that when we finally get reflections we could skip code generation step and generate graph based on structs and their attributes in runtime. Let's hope for C++23.
