### ISSUE TITLE
Chance of 3.X.X style generator being added as option to 4.X.X?

### ISSUE THREAD

**Issue by Coder666** [microsoft/cppgraphqlgen#210]
Hi,

We have spent several hours trying to upgrade to 4.X.X but have hit a problem that is keeping us locked to version 3.X.X. based around inheritance.  It's a bit too late for us to redesign or rewrite large chunks of our codebase so we are stuck at the moment on 3.X.X

Is it possible to make a suggestion/request for a 3.X.X inheritance based generator (using the new result types) as an option on the 4.X.X schemagen?

Thanks

**Comment by wravery** [comment]
Before doing that (because it's hard to maintain both), I've been thinking about writing a migration guide. Can you give me a little more detail about the kind of change that was more difficult in your project?

I haven't used this before, but I also wonder if some migration changes could be automated with clang-tidy. It would require a system with clang tools to perform the automatic migration, but then it could target other tool chains. But maybe there's a pattern in your project which is more difficult to handle.

The last alternative would be to generate interop classes which allow inheritance but internally use the type-erased version. Everyone would still need to fix the signatures on all their method overrides, but if inheritance is the only option this would mimic the 3.x hierarchy. Not sure of all the details, but I think this approach would help avoid reintroducing some of the complexity that came with the different options and defaults in 3.x.

**Comment by Coder666** [comment]
So we have some inheritance in the graphql schema with a large number of implementations, for example:

```
interface Node
{
    _id : ID!
}

type NodeTypeA implements Node
{
     _id : ID!
     ...
     ...
}


type NodeTypeB implements Node ...
type NodeTypeC implements Node ...
type NodeTypeD implements Node ...
type NodeTypeE implements Node ...
```

Unfortunatley we coupled our data layer to the generated 3.X.X class heirachy and as such it was simple to return an array of "Nodes" internally and perform filtering and other operations etc by downcasting before hitting graphql.   

Now with the 4.X.X system, the implementation pointer is locked away inside a Concept and is inaccessible which causes some issues, we can't downcast and we can't access the implementation object once it is contained by generated object.

Your suggestion of interop classes seems like a reasonable idea and it's more portable than using clang

**Comment by wravery** [comment]
So the problem is you can't access methods/members of the impl type from the array of type-erased wrappers?

I think something like this would work. Substitute your own impl base-class interface in your internal storage, and then store the array of that type which you can still downcast. Using `std::variant` like I did with `SharedHero` and `WeakHero` in the learn [sample](https://github.com/microsoft/cppgraphqlgen/blob/main/samples/learn/HeroData.h) adds some type safety, but you can use downcasting or virtual methods on the base class as you see fit. When you need a result of `std::vector<std::shared_ptr<object::Node>>`, use `std::transform` to fill it in with newly created type-erased wrappers.

If you had something like this in C++ before:

```cpp
class NodeTypeA : public object::NodeTypeA
{
...
};

class NodeTypeB : public object::NodeTypeB
{
...
};

std::vector<std::shared_ptr<service::Object>> nodes {
    std::make_shared<NodeTypeA>(),
    std::make_shared<NodeTypeB>(),
    ...
};
```
then it would change to something like this:
```cpp
class NodeTypeImpl
{
public:
    // Need to override this in the sub-classes to construct the correct sub-type wrappers.
    virtual std::shared_ptr<object::Node> make_node() const = 0;

    // Implement/declare the accessors you want to use without downcasting...
};

class NodeTypeA
    : public NodeTypeImpl
    , public std::enable_shared_from_this<NodeTypeA>
{
public:
    // Convert to a type-erased Node.
    std::shared_ptr<object::Node> make_node() const final
    {
        return std::make_shared<object::Node>(std::make_shared<object::NodeTypeA>(shared_from_this()));
    }
...
};

class NodeTypeB
    : public NodeTypeImpl
    , public std::enable_shared_from_this<NodeTypeB>
{
public:
    // Convert to a type-erased Node.
    std::shared_ptr<object::Node> make_node() const final
    {
        return std::make_shared<object::Node>(std::make_shared<object::NodeTypeB>(shared_from_this()));
    }
...
};

std::vector<std::shared_ptr<NodeTypeImpl>> nodes {
    std::make_shared<NodeTypeA>(),
    std::make_shared<NodeTypeB>(),
    ...
};

std::vector<std::shared_ptr<object::Node>> wrap_nodes()
{
    std::vector<std::shared_ptr<object::Node>> result(nodes.size());

    std::transform(nodes.cbegin(), nodes.cend(), result.begin(), [](const auto& node) {
        return node
            ? node->make_node()
            : std::shared_ptr<object::Node> {};
    });

    return result;
}
```
It's more boilerplate, but it has the advantage of making the vector of `nodes` more type safe than storing the `std::shared_ptr<service::Object>`, and your implementation hierarchy is decoupled from the generated code. You can avoid downcasting much of the time when operating on the `nodes` vector if you put your internal interface on the `NodeTypeImpl` base class, either as virtual methods or shared implementations when it doesn't depend on the sub-class to override it.

**Comment by wravery** [comment]
You may also be using multiple inheritance already to create a shared base class besides `service::Object` in your version of the `nodes` vector for greater type safety. In that case it should be easier to retrofit this approach just by adding something like the `make_node` virtual method.

**Comment by Coder666** [comment]
Thanks for your response, I will revisit our 4.X.X branch and try this approach

**Comment by wravery** [comment]
> With type erasure our code has to loop over lists now allocating additional memory for the graph objects and this is not great, the codebase became very complex.

If I'm understanding your comment correctly, I think you're referring to the loop/`std::transform` in my `wrap_nodes` example. Some of those loops can probably be avoided or amortized. This example demonstrates how to enable access to the strongly type object where before you would have had to either run through a loop performing a `std::static_pointer_cast<service::Object>` (or `shared_from_this`) on demand, or you would need to store the `std::shared_ptr<service::Object>` directly in your `std::vector`, which means you can't access the strongly typed contents anymore without unsafe down-casting (or RTTI-enabled dynamic casts). If you don't actually need access to the strongly typed objects anymore, you could use `std::vector<std::shared_ptr<object::NodeObject>>` for `nodes` and initialize it once with the type-erased implementation.

> What if I can create a PR with an option to generate server objects that can be interited from? Is this likley to be merged?

If there's something you'd like to backport to 3.x for use with an inheritance pattern, I'd be more likely to take that PR. I don't really want to mix the inheritance and type-erasure models in the same branch, the complexity and confusion that would introduce would be far worse in my opinion.
