### ISSUE TITLE
Feature request:  clientgen library allowing custom language plugins 

### ISSUE THREAD

**Issue by Coder666** [microsoft/cppgraphqlgen#211]
This is a very niche so fully understand if the answer is no

We have an embedded scripting language wrapper around the ```response::Value``` and are looking to generate client code that essentially does the same as a C++ generated client to avoid a JSON conversion step.  It would be nice if clientgen was more polymorphic so that we could add lambda callbacks or set an output object.

The idea being that we can change the language, by responding to callbacks or virtual/type erased function calls to output bits of the code i.e. `OutputStartOfScope`, `OutputEndOfScope`, `OutputStartOfFunction`,  `OutputVariable` etc

**Comment by wravery** [comment]
Depending on how dynamic this language is (does it need to declare response types?), maybe you could forego using the generated response struct and just send the `response::Value` through a type erased `response::Writer` which emits an object in your scripting language. It could emit a script string that is evaluated to generate it, or better, invoke the appropriate bindings to construct the object directly in the script environment.

If it does require a type declaration, then you might need 2 passes with different versions of the `Writer` to generate a runtime declaration based on the `Value` structure/contents.

The only case I can think of where this wouldn't work is if it's a precompiled language and it's not dynamic. You'd need a sample response with all possible values. Otherwise, I think you could build a function library that converts any type of `response::Value` to an object in the scripting language at runtime, without going through a JSON string.

**Comment by Coder666** [comment]
The generator_util library for example makes assumptions about the language, the feature request is really for an abstraction layer that allows me to replace all of this without duplicating the code:

```
const CppTypeMap SchemaLoader::s_builtinCppTypes = {
	"response::IntType"sv,
	"response::FloatType"sv,
	"response::StringType"sv,
	"response::BooleanType"sv,
	"response::IdType"sv,
};
```

Anyway I've closed this now, we will go down the code duplication route.
