### ISSUE TITLE
Example of subscription filtering with directives

### ISSUE THREAD

**Issue by Coder666** [microsoft/cppgraphqlgen#220]
Hi

Is there any example you could point me at which shows how to implement subscription filtering via directives?  

Our use-case is to have a regular expression directive on a field and only dispatch the subscribed object if the regular expression matches.  Is that possible or is there a better way to achieve the same result?

Thanks

**Comment by Coder666** [comment]
Please also note that we are on v3.7.1

**Comment by wravery** [comment]
The directive filtering is only supported for directives on the root field of the subscription, so I'm not sure if that matches your scenario. The gist of it is you would implement a `SubscriptionFilterCallback` `applyDirectives` function/lambda which gets called for each directive on the root field. If it returns `false` for any directive (e.g. evaluating a directive argument against a regular expression), then the event is not delivered to that subscription. I can't tell if you mean that you want to pass the regex in an argument to the directive, but I'd be very worried about taking untrusted input and parsing it as a regular expression. That seems like it would be difficult to sanitize reliably.

If you want to evaluate the regex against something in the event (e.g. a field name or value rather than a token in the directive arguments), then you'll probably need to capture that token in the `applyDirectives` lambda and look for a match on the directive name, then a match on the argument name and value. It's up to you whether non-matching directives or argument names should return true or false, effectively ignoring or blocking any other directives besides the regex one.

**Comment by Coder666** [comment]
`I can't tell if you mean that you want to pass the regex in an argument to the directive, but I'd be very worried about taking untrusted input and parsing it as a regular expression. That seems like it would be difficult to sanitize reliably.`

So an invalid regular expressions is a non-issue.  The graph is private to the application and regular expressions cannot be entered outside of development.

I spent some time on this today and it looks like I can't do what I want, to give a more specific example, lets say we have a subscription like this:

`
subscription example
{
      onThingHappened
      {
             nestedObject
             {
                    name @regExMatch( rx : ".*foo" )
             } 
      }
}
`

I am looking to drop/not deliver the request if regExMatch on the name field is true

As far as I can tell this is not possible.

**Comment by wravery** [comment]
> I am looking to drop/not deliver the request if regExMatch on the name field is true
> 
> As far as I can tell this is not possible.

Correct, not without modification. You'd need to move the directive to `onThingHappened` (the root field of the subscription), and you'd need to capture the value of `name` (or an interface/callback to extract it) in the `applyDirectives` lambda to match the regex against it.

**Comment by wravery** [comment]
Alternatively, while the subscription is being evaluated it has access to the directives on `name`, you could bubble up an error from the resolver, but then the error will still get delivered. It would at least short-circuit recursive resolvers if that's expensive enough to matter.

You could also filter the delivery after evaluation, in the `SubscriptionCallback`. For instance, if there's an error generated by evaluating the directive's regex in the resolver, you could ignore the event in the callback.

**Comment by Coder666** [comment]
ok, it looks like I will finally have to go down the route of forking the code.

I can probably throw a specific exception from a field getter to stop the subscription firing or alternativley I can maybe move the directive evaluation to after the query is resolved and pass the resolved result in to the applyDirectives callback.   I'll take a look tomorrow

Thanks once again for your help and your fast response.
