### ISSUE TITLE
Feature request: Make service classes able to be inherited from

### ISSUE THREAD

**Issue by Coder666** [microsoft/cppgraphqlgen#221]
Hi

We previously discussed in #220 about filtering subscriptions at the field level using directives.  To achieve this in an efficient manner I am going to need to make some tweaks to the resolver.  I also have a number of other changes I wish to make, for example I will be adding optional callbacks that allow the resolver state to be used to determine if the operation should be aborted, instead of throwing exceptions.

I am not a fan of forking third party libraries because applying future bug fix patches can rapidly become a nightmare.  

So my (ideal) plan is to make the required modifications by subclassing the service and/or other required classes.  My problem is that the way these classes are written they are not easily subclassable/customisable.

Would it be possible raise a feature request for the service classes able to be more easily inherited from?  

For example: 

- make resolve function on the service::Object virtual
- add protected data member getters (return const & non-const ref)

Thanks

**Comment by Coder666** [comment]
Ok, here is how I have dealth with this.  

Firstly I have added a new type:

```
struct DeliveryState : std::enable_shared_from_this<DeliveryState>
{
	virtual bool deliver() const
	{
		return true;
	}
};
```

and a since we need a new state for each delivery callback, there is a "factory" method for creating these objects

```using SubscriptionDeliveryStateCallback = std::function<std::shared_ptr<DeliveryState>()>;```

The callback held in the SubScriptionParams

```
struct SubscriptionParams
{
	SubscriptionDeliveryStateCallback createDeliveryState;
	std::shared_ptr<RequestState> state;
	peg::ast query;
	std::string operationName;
	response::Value variables;
};
```

This is then further stored in ```SubscriptionData```

```
struct SubscriptionData : std::enable_shared_from_this<SubscriptionData>
{
        ...
	...
	...
	SubscriptionDeliveryStateCallback createDeliveryState;
};
```

Now inside the delivery loop, a new DeliveryState is created for each subscription using the factory function.   And it is set on the ```SelectionSetParams``` which are passed to the object resolver function

```
struct SelectionSetParams
{
	...
        ...
        ...
	const std::shared_ptr<DeliveryState>& deliveryState;
};
```

During the async lambda in the object resolver we capture the deliveryState from the SelectionSetParams and it can then be checked and we can early out of the loop

```
                        for (auto& child : children)
			{
				auto name = child.first;

				try
				{
					auto value = child.second.get();

					if (deliveryState && deliveryState->deliver() == false)
					{
						break;
					}

```

The deliveryState can then be passed into the subscription callback as an additional parameter, and after the evaluation of the std::future value, it can be checked to see if the deliveryState indicates that the data should be examined/delivered

```
void subCallback( const std::shared_ptr<DeliveryState>& state, std::future< Value > v )
{
     auto x = v.get();
     if( state->deliver() )
     {
         ....
     }
}
```

I'm sure there are 100 other better ways to do this, but I specifically need to avoid just throwing an exception since this will be filtering out subscription events, we can assume that 95% of the time it would throw an exception so this way makes the most sense to me.

Anyway if anyone else has a similar use case, here is an idea on how to implement it.

**Comment by wravery** [comment]
This is a follow-up to #220. Some of the suggestions there about throwing an exception to return an error from this field were based on the premise that you'd want to short-circuit evaluation of potentially expensive recursive resolvers, but it sounds like you're OK with evaluating the payload for the subscription, you just don't want to call the `service::SubscriptionCallback`.

> The deliveryState can then be passed into the subscription callback as an additional parameter, and after the evaluation of the std::future value, it can be checked to see if the deliveryState indicates that the data should be examined/delivered
> 
> ```
> void subCallback( const std::shared_ptr<DeliveryState>& state, std::future< Value > v )
> {
>      auto x = v.get();
>      if( state->deliver() )
>      {
>          ....
>      }
> }
> ```

Since you have evaluated the future at this point, the way I'd handle this would be to combine it with the `service::SubscriptionCallback`, possibly using a [higher-order function](https://en.wikipedia.org/wiki/Higher-order_function) to generate the filtering callback:

```cpp
using DeliveryFilterCallback = std::function<bool(const response::Value&)>;

service::SubscriptionCallback createSubCallback(DeliveryFilterCallback&& filter, service::SubscriptionCallback&& callback)
{
	return [deliveryFilter = std::move(filter), maybeCallback = std::move(callback)](std::future<response::Value> payload)
	{
		// This would be a little simpler in v4.x. The SubscriptionCallback takes a response::Value instead of a
		// std::future<response::Value>, so we wouldn't need to resolve the future or re-wrap it in a promise
		// to call maybeCallback.
		auto value = payload.get();

		if (deliveryFilter(value))
		{
			std::promise<response::Value> promise;

			promise.set_value(std::move(value));
			maybeCallback(promise.get_future());
		}
	};
}
```

You could also embed more information in the `service::RequestState`, to make it available to both the resolvers (automatic) and your filter (by capturing it in your filter callback). For example, if you want to filter based on a regular expression, instead of embedding it in the query as a directive, you could make it a member of your `service::RequestState` sub-class. Then you could both short-circuit expensive recursive calls (if a field is nullable, it can return null instead of throwing an exception), and filter delivery based on the same member in the `service::RequestState`.
