### ISSUE TITLE
Clientgen usage

### ISSUE THREAD

**Issue by panthers-00** [microsoft/cppgraphqlgen#261]
Hello, 
Is there a guide on the usage of the schemagen and clientgen tool? I have a schema.graphql file with multiple queries. But I am unsure on how to generate the client. In particular, I do not know what needs to be provided for the --request parameter for clientgen.

**Comment by wravery** [comment]
There's some mention of it in the [README](https://github.com/microsoft/cppgraphqlgen/blob/main/README.md), but not much more than you get from running either tool with the `--help` parameter. There's also some description of the [CMake helpers](https://github.com/microsoft/cppgraphqlgen/blob/main/doc/migration.md#cmake-changes) section in the migration guide, if you are using CMake I'd encourage you to use them.

Specifically for the `--request` parameter, `clientgen` needs 2 separate documents/files:
1. The schema document for the service that's going to resolve the queries, so it knows what types to expect for the fields.
2. The request document, which may contain multiple queries as long as no more than 1 of them is unnamed.

You can't mix them in the same file, either. In fact, the GraphQL spec says that only executable queries are allowed in an [ExecutableDocument](https://spec.graphql.org/October2021/#ExecutableDocument).

The `schemagen` tool only requires the first document since it builds a service which supports any query, and not just hardcoded ones. You can parse arbitrary queries at runtime to execute with the service using the functions in [graphqlservice/GraphQLParse.h](https://github.com/microsoft/cppgraphqlgen/blob/main/include/graphqlservice/GraphQLParse.h).
