### ISSUE TITLE
cppgraphqlgen thread safety questions

### ISSUE THREAD

**Issue by h-barthwal** [microsoft/cppgraphqlgen#281]
First of all, thanks for writing this fantastic library. I have a few questions about its thread safety:
1. Is is safe to use static `Schema` object in a concurrent application (in my case it is a webservice running >50 threads)? The reason I am asking this is that I ended up disabling query validation (by setting `query_syntax_tree.validated = true`) when I observed crashes in my app that seemed to be happening within the validation code-path under high concurrency. I believe this was version 3.5.x. 

2. I am currently running version 4.5.0 and considering having `thread_local` schema object to avoid any threading related issues. But that won't really help if `cppgraphqlgen` uses any non `thread_local static`s (that are not guaranteed to be thread safe) within its implementation or the generated code. So far I can only see one `static` within the generated `GetSchema()` function (which I can change to `thread_local`). Are there other such places?

Thanks in advance.

**Comment by wravery** [comment]
Generally speaking, the library and all of the code it generates is expected to be thread-safe. There are mutexes in the latest version protecting the schema validation and subscription members: https://github.com/microsoft/cppgraphqlgen/blob/7f0e1661fcdf21a19ea6c826f136c7d2e95d085b/include/graphqlservice/GraphQLService.h#L1462. However, it's possible that if you're creating multiple instances of the `Operations`/`Request` object for use on separate threads that they're sharing static data returned from `GetSchema` and "protecting" them with separate mutexes (meaning they're not really protected).

This is a legitimate way to handle concurrency, and the cost of building the schema is paid once per `Operations` instance, not per call to `resolve`, so I think in retrospect that it was a mistake to cache it in a `std::weak_ptr` in the generated `GetSchema` function. Each instance of `Operation` can and should have its own copy of the schema.

**Comment by h-barthwal** [comment]
Thanks for the quick response. I will go ahead and make the `Schema` object non-`static`.

**Comment by wravery** [comment]
@h-barthwal, I just reviewed the `graphql::introspection::Schema` type, and I think it should be thread safe as well. It has some mutable members where it tracks `LIST` and `NON_NULL` wrapper types which are instantiated on-demand, but those are protected with `std::shared_mutex` for read/write lock functionality, and they return copies of the `std::shared_ptr` inside the map rather than an iterator which could be invalidated.

It's possible that the 3.5 version had some thread-safety issues that have been fixed since then, but I don't think changing the `GetSchema` static variable to thread-local should be necessary. If you still run into thread-safety issues in 4.5, with or without that change, please let me know. Thanks!
